name: shieldiea
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  firebase_messaging: ^14.0.0
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.20.0
  firebase_core: ^2.7.0
  image: ^4.5.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  # flutter_local_notifications: ^17.0.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  shared_preferences: ^2.5.3
  supercharged: ^2.1.1
  http: ^1.4.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - assets/scripts/
    - assets/images/
    - assets/icons/
    - assets/lottie/
  uses-material-design: true
